title: spencercmd
description: we are blog
url: "https://spencercmd.github.io"
baseurl: ""

# Build settings
markdown: kramdown
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Author info
author:
  name: Spencer Livingston
  email: spencer@spencercmd.com

# Social links (optional)
github_username: spencercmd
twitter_username: spencercmd